ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

# string = "ABBA"
string = "NFXCFQTZDREFKLCGRDVQIKYTPKIRGJNPKFYTVZGNFCRZQUUFYTZBKJPQJNZZZIVCPKIRZZIVKRSYTPNFBCLGZTJFNFKFXERKJPEFISFVZEFAVIDPERNVZQUFGJNVZJRQJRCXFDVZBERIDPEJVQTNFIKLAPERNVZQUFGJBRKRZZIVCPKIRDVZTIRGJNVQPKFYTVZGLEFZCRKRSFXVZTVQIKQRIFFXVKJFQJFXVEIVTERGLEFZCRKRSFXVKJRELNUPYTLIRARQUIVZNKFGZBELUCVDVEFTPNYTVQIGPIVKQTRZTJVZQURNUFKJVQIFXQNREVZTIRKREVENFCXVALBPQJBZENZTVQIG"

res = ""

for char in string:
	res	+= ALPHA[25 - ALPHA.find(char)]

print(res)
