ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
CIPHER = "URODZINYABCEFGHJKLMPQSTVWX"

msg = "ZYCIEBOWIEMSKLADASIEZCZEGOSWIECEJNIZTYLKOSZEREGICYFRILITER"
res = ""

for char in msg:
	index = ALPHABET.find(char)
	res += CIPHER[index]

print(res)